event_manager/event_manager/urls.py
"""
PROJEKT URLs
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from events.api.urls import router

urlpatterns = [
    path("", include("frontend.urls")),
    path("admin/", admin.site.urls),
    path("events/", include("events.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("token", obtain_auth_token, name="token"),  # hier den token holen
    path("api/", include(router.urls)),
    path(
        "schema/",
        SpectacularAPIView.as_view(api_version="v2"),
        name="schema",
    ),
    path(
        "docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

event_manager/events/urls.py
"""
URLs der App events

/events/hello
/events/show

Aufgabe
Route: /events/show
View show anlegen, die das Request-objekt ausgibt
mit print(dir(request))
Rückgabe: show

pfad-Funktion benötigt drei Argumente:
- Pfad-Anteil
- Funktionsreferenz
- Name des Pfades (muss nicht Funktionsname sein)

http://127.0.0.1:8000/events/event/2
"""
from django.urls import path
from . import views

# app_name um im Template auf die App zu referenziern
app_name = "events"

urlpatterns = [
    path("", views.events, name="events"),
    path("event/<int:pk>", views.event_detail, name="event_detail"),
    path("category/create", views.category_create, name="category_create"),
    # path("category/add", views.CategoryCreateView.as_view(), name="category_add"),
    path("event/create", views.EventCreateView.as_view(), name="event_create"),
    path("event/<int:pk>/update", views.EventUpdateView.as_view(), name="event_update"),
    path("event/<int:pk>/delete", views.EventDeleteView.as_view(), name="event_delete"),
    path("hello", views.hello_world, name="hello_world"),
    path("show", views.show, name="show"),
    path("categories", views.categories, name="categories"),
]

event_manager/event_manager/templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
<html lang='{{ LANGUAGE_CODE }}' class="h-100">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="author" content="{% block author %}{% endblock %}">
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

</head>

<body class="d-flex flex-column h-100">


    <header class="p-3 bg-dark text-white">

        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">

                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"
                    style="margin-left:120px;">

                    <li><a href="{% url 'events:events' %}" class="nav-link px-2
                  text-white">Events</a></li>

                    <li><a href="{% url 'events:categories' %}" class="nav-link px-2
                  text-white">Kategorien</a></li>
                </ul>

                <form action="" method="get" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                    <input name="q" required="required" type="search" class="form-control form-control-dark"
                        placeholder="Search..." aria-label="Search">
                </form>

                <div class="text-end">

                    {% if user.is_authenticated %}

                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32"
                                class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                            <a class="dropdown-item">Hello {{user}}!</a>
                            <!-- LOGOUT: Freischalten, wenn der Login und Signup implementiert wird -->
                            <li>
                                <a class="dropdown-item" href="{% url 'logout' %}">Sign out</a>
                            </li>
                        </ul>
                    </div>

                    {% else %}


                    <!-- das Freischalten, wenn der Login und Signup implementiert wird -->
                    <a href="{% url 'login' %}">
                        <button type="button" class="btn btn-outline-light me-2">Login</button>
                    </a>


                    {% comment %}
                    <!-- das Freischalten, wenn der Login und Signup implementiert wird -->
                    <a href="{% url 'user:signup' %}">
                        {% endcomment %}
                        <a href="">
                            <button type="button" class="btn btn-warning">Sign-up</button>
                        </a>

                        {% endif %}
                </div>
            </div>
        </div>
    </header>

    <main class="flex-shrink-0">

        <div class="container">
            <div class="row">
                <div class="col-12" style="margin-top:25px;">
                    {% block head %}{% endblock %}
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                {% block content %}{% endblock %}
            </div>
        </div>

    </main>


    <footer class="footer mt-auto py-3 text-light bg-dark">
        <div class="container">
            <p class="float-end mb-1">
                <a href="#">Back to top</a>
            </p>
            <h3 class="mb-1">Event Manager</h3>
            <p class="mb-0">Neu in Django? <a href="/">Visit the Pingu homepage</a>
                oder <a href="https://djangoheroes.spielprinzip.com">Leg los mit Django</a>.</p>
        </div>
    </footer>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>