event_manager/event_manager/urls.py
"""
PROJEKT URLs
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from events.api.urls import router

urlpatterns = [
    path("", include("frontend.urls")),
    path("admin/", admin.site.urls),
    path("events/", include("events.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("token", obtain_auth_token, name="token"),  # hier den token holen
    path("api/", include(router.urls)),
    path(
        "schema/",
        SpectacularAPIView.as_view(api_version="v2"),
        name="schema",
    ),
    path(
        "docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

event_manager/events/api/urls.py
from rest_framework import routers
from . import views

# Default Router erstellt alle URLs für diesen Endpunkt
router = routers.DefaultRouter()
router.register("category", views.CategoryViewSet)
router.register("event", views.EventViewSet)

event_manager/events/urls.py
"""
URLs der App events

/events/hello
/events/show

Aufgabe
Route: /events/show
View show anlegen, die das Request-objekt ausgibt
mit print(dir(request))
Rückgabe: show

pfad-Funktion benötigt drei Argumente:
- Pfad-Anteil
- Funktionsreferenz
- Name des Pfades (muss nicht Funktionsname sein)

http://127.0.0.1:8000/events/event/2
"""
from django.urls import path
from . import views

# app_name um im Template auf die App zu referenziern
app_name = "events"

urlpatterns = [
    path("", views.events, name="events"),
    path("event/<int:pk>", views.event_detail, name="event_detail"),
    path("category/create", views.category_create, name="category_create"),
    # path("category/add", views.CategoryCreateView.as_view(), name="category_add"),
    path("event/create", views.EventCreateView.as_view(), name="event_create"),
    path("event/<int:pk>/update", views.EventUpdateView.as_view(), name="event_update"),
    path("event/<int:pk>/delete", views.EventDeleteView.as_view(), name="event_delete"),
    path("hello", views.hello_world, name="hello_world"),
    path("show", views.show, name="show"),
    path("categories", views.categories, name="categories"),
]

event_manager/events/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from .validators import date_in_past, BadWordFilter

User = get_user_model()  # bezieht immer das aktuelle Usermodel

# from event_manager.mixins import DateMixin


class DateMixin(models.Model):
    # lege beim Erstellen den aktuellen Zeitstempel an
    created_at = models.DateTimeField(auto_now_add=True)
    # setze Zeitstempel wenn das Model aktualisiert wird
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(DateMixin):
    """Jedes Model muss von models.Model erben. Aus einem Model kann man
    eine DB-Tabelle erstellen oder ein Formular rendern lassen."""

    class Meta:
        verbose_name_plural = "Categories"
        verbose_name = "Category"
        # db_table = "cats"  # alternativer Tabellenname

    name = models.CharField(max_length=100)  # VARCHAR 100
    sub_title = models.CharField(max_length=200, null=True, blank=True)

    # null=darf in der DB null sein. blank=darf im Formular leer sein.
    description = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        """String Repräsentation des Category Objects"""
        return self.name


class Event(DateMixin):
    """ein Event in der Zukunft, zb. Tennis im Stadtpark."""

    class GroupSize(models.IntegerChoices):
        """Enum mit Gruppengrössen"""

        SMALL = 5, "kleine Gruppe"
        BIG = 10, "mittelgrosse Gruppe"
        LARGE = 20, "sehr große Gruppe"
        UNLIMITED = 0, "ohne Begrenzung"

    name = models.CharField(
        max_length=150,
        validators=[MinLengthValidator(3)],
    )  # , unique=True
    sub_title = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        validators=[BadWordFilter(["evil", "doofi"])],
    )
    description = models.TextField(null=True, blank=True)
    date = models.DateTimeField(validators=[date_in_past])
    min_group = models.PositiveIntegerField(choices=GroupSize.choices)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="events"
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="events")
    is_active = models.BooleanField(default=True)

    def clean(self):
        """Crossfield Validation"""
        if self.name == self.sub_title:
            raise ValidationError("name und sub_title dürfen nicht gleich sein!")
        super().clean()

    def __str__(self) -> str:
        return self.name

event_manager/events/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Event, Category


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        # fields = "__all__"
        # fields = ("name", "sub_title")
        exclude = ("author",)

        widgets = {
            "date": forms.DateInput(
                format=("%Y-%m-%d %H:%M"), attrs={"type": "datetime-local"}
            ),
        }

        labels = {
            "sub_title": "Genre",
        }

    def clean_sub_title(self):
        """
        ### asdsdaf ###
        d = {
            "a": 1
        }
        d["a"]
        d.get("a", "")

        """
        sub_title = self.cleaned_data["sub_title"]

        if isinstance(sub_title, str) and "@" in sub_title:
            raise ValidationError("im Subtitle darf kein @ sein")

        return sub_title


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"

event_manager/events/api/views.py
"""
Viewset: beinhaltet alle API-Endpunkte automatisch
"""
from rest_framework import viewsets, permissions, authentication
from events import models

from . import serializers
from . import permissions


class EventViewSet(viewsets.ModelViewSet):
    serializer_class = serializers.EventSerializer
    queryset = models.Event.objects.all()
    permission_classes = [permissions.IsAdminUserOrReadOnly]
    authentication_classes = [authentication.TokenAuthentication]

    def perform_create(self, serializer):
        """Wird aufgerufen, bevor das Objekt angelegt wird."""
        author = self.request.user
        serializer.save(author=author)


class CategoryViewSet(viewsets.ModelViewSet):
    """
    get, post, patch, put
    """

    serializer_class = serializers.CategorySerializer
    queryset = models.Category.objects.all()

event_manager/events/views.py
from typing import Optional
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.http import HttpResponse
from .models import Category, Event
from .forms import CategoryForm, EventForm


class UserIsOwner(UserPassesTestMixin):
    def test_func(self) -> bool:
        """prüfe, ob der aktuelle User der Eigentümer des Events ist.
        Oder User ist Admin user"""
        return (
            self.get_object().author == self.request.user
            or self.request.user.is_superuser
        )


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy("events:categories")


class EventCreateView(LoginRequiredMixin, CreateView):
    # event_form.html
    model = Event
    form_class = EventForm
    # success_url = reverse_lazy("events:events")

    def form_valid(self, form):
        """Kurz vor dem Speichern Formulardaten nochmal ändern
        und mit super() die Methode der Elternklasse aufrufen"""
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("events:event_detail", args=(self.object.pk,))


class EventUpdateView(UserIsOwner, UpdateView):
    # event_form.html
    model = Event
    form_class = EventForm
    success_url = reverse_lazy("events:events")


class EventDeleteView(UserIsOwner, DeleteView):
    # generisches Formular ist event_confirm_delete.html
    model = Event
    success_url = reverse_lazy("events:events")


def category_create(request):
    """
    neues Category anlegen
    events/category/create
    """
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("events:categories")

    else:
        # hier soll leeres Formular erzeugt werden
        form = CategoryForm()

    return render(request, "events/category_form.html", {"form": form})


def events(request):
    """
    events/

    """
    events = Event.objects.select_related("category", "author").all()
    return render(request, "events/events.html", {"events": events})


def event_detail(request, pk):
    """
    Dank Platzhalter in events/urls.py steht mir pk als Funktionsparameter
    zur Verfüfung.
    """
    # try:
    #     event = Event.objects.get(pk=pk)
    # except Event.DoesNotExist:
    #     raise Http404("sorry")
    event = get_object_or_404(Event, pk=pk)
    return render(request, "events/event_detail.html", {"event": event})


def categories(request):
    """
    events/categories
    """
    categories = Category.objects.all()
    return render(request, "events/categories.html", {"categories": categories})


def show(request) -> HttpResponse:
    """analysiere Request Objekt"""
    print(request.META)
    print("GET VALUES:", request.GET)
    if "id" in request.GET:
        print("ID:", request.GET["id"])
    print("USER: ", request.user)
    print("METHOD:", request.method)
    return HttpResponse("<h1>show</h1>")


def hello_world(request) -> HttpResponse:
    """
    jede View bekommt ein request-Objekt übergeben und
    muss ein HTTPResponse-Objekt zurückgeben.
    Aussnahme: eine Exception wird ausgelöst
    """
    return HttpResponse("hello world")

event_manager/events/templates/events/categories.html
{% extends "base.html" %}

{% block title %}
Übersicht der Kategorien
{% endblock %}

{% block head %}
<h1>Übersicht der Kategorien</h1>
{% endblock %}

{% block content %}

<a href="{% url 'events:category_create' %}">neue Kategorie anlegen</a>

{% if categories.exists %}
<p>Anzahl der Kategorien: {{categories|length}}</p>
{% else %}
<p>keine Kategorien vorhanden</p>
{% endif %}

<ul>
    {% for category in categories %}
    <li>{{category}}</li>
    {% endfor %}
</ul>
{% endblock %}

event_manager/events/templates/events/category_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
neue Kategorie anlegen
{% endblock %}

{% block head %}
<h1>neue Kategorie anlegen</h1>
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <div>
        <input type="submit" value="Formular absenden" />
    </div>
</form>
{% endblock %}

event_manager/events/templates/events/event_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Event löschen
{% endblock %}

{% block head %}
<h1>Event {{object}} löschen</h1>
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>
        Willst du das Objekt {{object}} wirklich löschen?
    </p>
    <div>
        <input type="submit" value="Objekt löschen" />
    </div>
</form>
{% endblock %}

event_manager/events/templates/events/event_detail.html
{% extends "base.html" %}

{% block title %}
{{event.name}}
{% endblock %}

{% block head %}
<h1>{{event.name}}</h1>
{% endblock %}

{% block content %}

{% if user == event.author or user.is_superuser %}
<a href="{% url 'events:event_update' event.pk %}">Event editieren</a>
{% endif %}

<p>
    <a href="{% url 'events:events' %}">zurück zur Übersicht</a>
</p>
<p>{{event.name}}</p>
<p>findet statt am {{event.date}}</p>
{% endblock %}

event_manager/events/templates/events/event_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}

{% if object %}
Event updaten
{% else %}
Event eintragen
{% endif %}

{% endblock %}

{% block head %}
{% if object %}
<h1>Event {{object}} updaten</h1>
{% else %}
<h1>neuen Event anlegen</h1>
{% endif %}

{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <div>
        <input type="submit" value="Formular absenden" />
    </div>
</form>
{% endblock %}

event_manager/events/templates/events/events.html
{% extends "base.html" %}

{% block title %}
Übersicht der Events
{% endblock %}

{% block head %}
<h1>Übersicht der Events</h1>
{% endblock %}


{% block content %}
<p>
    <a href="{% url 'events:event_create' %}">neuen Event anlegen</a>
</p>

<ul>
    {% for event in events %}
    <li>
        <a href="{% url 'events:event_detail' event.pk  %}">
            {{event}} [{{event.category.name}}]
        </a>

        [<a href="{% url 'events:event_delete' event.pk  %}">
            löschen
        </a>]
        ({{event.author}})

    </li>
    {% endfor %}
</ul>
{% endblock %}